version: '3.6'

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "5000"
    restart: always

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
    - 80:80
    depends_on:
    - web
